[package]
authors = ["Loïc Damien <loic.damien@dzamlo.ch>"]
name = "netlink-packet-netfilter"
version = "0.3.0"
edition = "2018"

homepage = "https://github.com/rust-netlink/netlink-packet-netfilter"
keywords = ["netlink", "linux", "netfilter"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rust-netlink/netlink-packet-netfilter"
description = "netlink packet types for the netfilter subprotocol"

[dependencies]
netlink-packet-core = { version = "0.9.0" }
bitflags = "2.10.0"
libc = "0.2.77"
derive_more = "0.99.16"
zerocopy = { version = "0.8", features = ["derive"] }

[dev-dependencies]
netlink-sys = { version = "0.8.3" }
